# game settings
import math

RES = WIDTH, HIGH = 1600, 900
FPS = 60
HALF_HIGH = HIGH // 2
HALF_WIDTH = WIDTH // 2
FOV_HIGH = HIGH // 3 * 2

PLAYER_POS = 11, 12
PLAYER_ANGLE = -math.pi / 2
PLAYER_SPEED = 0.04
PLAYER_SPEED_RUN = PLAYER_SPEED * 2
PLAYER_ROT_SPEED = 0.02
PLAYER_SIZE = 15
MOUSE_SPEED = 20

NPC_SPEED = 0.06
CHANGE_TIME = [7, 20, 5, 20, 5, 20, 5, 1200]

FOV = math.pi * 70 / 180
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS
FLOOR_COLOR = (40, 40, 40)

TEXTURE_SIZE = 1024
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

TEST_SIZE = 20
NPC_DRAW = False
